/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mypack;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Wali
 */
public class AddBooking extends javax.swing.JInternalFrame implements Printable {

    /**
     * Creates new form AdminLogin
     */
    
    Connection con=null;
    Statement st;
    ResultSet rs;
    
    String Ticketid;
    String Name;
    String Route;
    String From;
    String To;
    String BusNum;
    String Date;
    String Time;
    String BookDate;
    String SeatNum;
    String Price;
    
    
    
    public AddBooking() {
        initComponents();
        con= Connect.ConnectDB();
        try 
        {
         
            st = con.createStatement();
        
        rs=st.executeQuery("select R_Name from TB_Route");
            while(rs.next())
        {
        cmbroute.addItem(rs.getString(1));
        }
         /*rs=st.executeQuery("select Bus_Number from TB_Buses");
        while(rs.next())
        {
        cmbbusnum.addItem(rs.getString(1));
        }*/
            
            
        
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Connection Error !");
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtstartstop = new javax.swing.JTextField();
        txtnic = new javax.swing.JTextField();
        cmbroute = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtavseats = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtbook = new javax.swing.JTextField();
        txtbusnum = new javax.swing.JTextField();
        cmblaststop = new javax.swing.JComboBox();
        btncheck = new javax.swing.JButton();
        cmbnic = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtd = new javax.swing.JLabel();
        txtt = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cmbseat = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setBorder(null);
        setClosable(true);
        setTitle("Booking Window");
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/create-ticket-icon.png"))); // NOI18N
        setVisible(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Route");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Bus Number");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("From");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("To");

        txtstartstop.setEditable(false);
        txtstartstop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtnic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cmbroute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  " }));
        cmbroute.setToolTipText("");
        cmbroute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbrouteMouseClicked(evt);
            }
        });
        cmbroute.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbrouteItemStateChanged(evt);
            }
        });
        cmbroute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbrouteActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Seat Number");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirm");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Available Seats");

        txtavseats.setEditable(false);
        txtavseats.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtavseats.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Booked Seats");

        txtbook.setEditable(false);
        txtbook.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtbook.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtbusnum.setEditable(false);
        txtbusnum.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        cmblaststop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  " }));
        cmblaststop.setToolTipText("");
        cmblaststop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmblaststopMouseClicked(evt);
            }
        });
        cmblaststop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmblaststopItemStateChanged(evt);
            }
        });
        cmblaststop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmblaststopActionPerformed(evt);
            }
        });

        btncheck.setBackground(new java.awt.Color(0, 0, 0));
        btncheck.setForeground(new java.awt.Color(255, 255, 255));
        btncheck.setText("Check");
        btncheck.setToolTipText("Check whether the customer is Registered or not");
        btncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckActionPerformed(evt);
            }
        });

        cmbnic.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "NIC", "Name" }));
        cmbnic.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbnicItemStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Timings");

        txtd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        txtt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Name");

        txtname.setEditable(false);
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Age");

        txtage.setEditable(false);
        txtage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txtfname.setEditable(false);
        txtfname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("FatherName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtbusnum, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtstartstop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cmblaststop, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(cmbroute, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12))
                                    .addComponent(cmbseat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(30, 30, 30)
                                                    .addComponent(txtavseats, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtbook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btncheck, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 13, Short.MAX_VALUE)))
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(51, 51, 51))
                                            .addComponent(txtd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(jButton1)
                                .addGap(41, 41, 41)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cmbnic, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
            .addComponent(jSeparator1)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtd, txtt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbroute, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbusnum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstartstop, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmblaststop, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtavseats, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(116, 116, 116))
        );

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setText("Booking Window");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel4))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        if( txtstartstop.getText().equals("") || txtbusnum.getText().equals("")
                || txtnic.getText().equals("") || txtname.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this, "Error ! \n"
                    + "Please Check All the fields again");
        }
        else
        {
        String cnic = "'" +  txtnic.getText() + "'";
        String fname = "'" +  txtfname.getText() + "'";
        String route = "'" + cmbroute.getSelectedItem().toString() + "'";
        String busnum = "'" + txtbusnum.getText() + "'";
        String sstop= "'" + txtstartstop.getText() + "'";
        String estop = "'" + cmblaststop.getSelectedItem().toString() + "'";
        String comboseat = "'" + cmbseat.getSelectedItem().toString() + "'";
        String cmb= cmbnic.getSelectedItem().toString();
        
       if(cmb.equals("NIC"))
       { 
              
              
                try
                {
               
                
st.executeUpdate("Declare @Custid int set @custid=(select Cust_ID from TB_customer where Cust_Cnic = "+cnic+") declare @routid int set @routid=(select Rout_id From TB_Routinee where R_id= (select R_Id from TB_Route where R_Name = "+route+")) declare @bid int set @bid=(select Bus_id from TB_Buses Where Bus_Number="+busnum+")insert into TB_Booking values (@custid,@routid,@bid, "+sstop+", "+estop+" ,default,default,getdate(),"+comboseat+",default)");
                 
               // JOptionPane.showMessageDialog(this, "Ticket Booked");
                
              int a = JOptionPane.showConfirmDialog(this, "Booking Completed . Press Yes to Print This Ticket", "Confirm", JOptionPane.OK_OPTION);
              if(a == 0)
              {
                    PrinterJob job = PrinterJob.getPrinterJob();
                    job.setPrintable(this);
                    boolean ok = job.printDialog();
                    if (ok) {
                        try {
                             job.print();
               } catch (PrinterException ex) {
                /* The job did not successfully complete */
                   ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Check Your Printer Settings");
               }
                             }
                
              }
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, "Error ! Please Try Again");
                }
          }
          else if(cmb.equals("Name"))
          {
              try
                {
              
                
st.executeUpdate("Declare @Custid int set @custid=(select Cust_ID from TB_customer where Cust_Name = "+cnic+" and Cust_FName="+fname+") declare @routid int set @routid=(select Rout_id From TB_Routinee where R_id= (select R_Id from TB_Route where R_Name = "+route+")) declare @bid int set @bid=(select Bus_id from TB_Buses Where Bus_Number="+busnum+")insert into TB_Booking values (@custid,@routid,@bid, "+sstop+", "+estop+" ,default,default,getdate(),"+comboseat+",default)");
                 
               // JOptionPane.showMessageDialog(this, "Data Saved");
               
              int a = JOptionPane.showConfirmDialog(this, "Booking Completed . Press Yes to Print This Ticket", "Confirm", JOptionPane.OK_OPTION);
              if(a == 0)
              {
                    PrinterJob job = PrinterJob.getPrinterJob();
                    job.setPrintable(this);
                    boolean ok = job.printDialog();
                    if (ok) {
                        try {
                             job.print();
               } catch (PrinterException ex) {
                /* The job did not successfully complete */
                    
               }
                             }
                
              }
                }catch(Exception e)
                {
                    JOptionPane.showMessageDialog(this, "Error ! Please Try Again!");
                }
          }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed
   
 
    
    private void cmbrouteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbrouteItemStateChanged
         cmblaststop.removeAllItems();
         txtbusnum.setText("");
         txtstartstop.setText("");
         txtavseats.setText("");
         txtbook.setText("");
         txtd.setText("");
         txtt.setText("");
         cmbseat.removeAllItems();
         
         String cmb= "'" + cmbroute.getSelectedItem().toString()+ "'";
               
         try {
             
            rs=st.executeQuery("  select Bus_Number from TB_Buses where bus_id=(select bus_id from TB_Routinee where R_id=(select R_id from TB_Route where R_Name="+cmb+"))    ");
            
            while(rs.next())
            {
            txtbusnum.setText(rs.getString(1));
            }
            rs=st.executeQuery("  select R_Start from TB_Route where R_id=(select R_id from TB_Route where R_Name="+cmb+")    ");
            
            while(rs.next())
            {
            txtstartstop.setText(rs.getString(1));
            }
            rs=st.executeQuery(" select RC_StopName from TB_RouteCover where R_id=(select R_id from TB_Route where R_Name="+cmb+")    ");
            
            while(rs.next())
            {
            cmblaststop.addItem(rs.getString(1));
            }
            
            rs=st.executeQuery(" select Av_seats from TB_Booking where Rout_id=(select Rout_id from TB_Routinee where R_id=(select R_id from TB_Route where R_Name="+cmb+"))    ");
            
            while(rs.next())
            {
            txtavseats.setText(rs.getString(1));
            }
            
            rs=st.executeQuery(" select Rout_Date from TB_Routinee where Rout_id=(select Rout_id from TB_Routinee where R_id=(select R_id from TB_Route where R_Name="+cmb+"))    ");
            while(rs.next())
            {
            txtd.setText(rs.getString(1));
            }
            rs=st.executeQuery(" select Rout_Time from TB_Routinee where Rout_id=(select Rout_id from TB_Routinee where R_id=(select R_id from TB_Route where R_Name="+cmb+"))    ");
            
            while(rs.next())
            {
            txtt.setText(rs.getString(1));
            }
            
            rs=st.executeQuery(" select Booked_seats from TB_Booking where Rout_id=(select Rout_id from TB_Routinee where R_id=(select R_id from TB_Route where R_Name="+cmb+"))    ");
            while(rs.next())
            {
            txtbook.setText(rs.getString(1));
            }
            
            rs=st.executeQuery(" select Bus_Capacity from TB_Buses where bus_number='"+ txtbusnum.getText() +"'    ");
            while(rs.next())
            {   
                int cap= rs.getInt(1);
                
                for (int i = 1; i <= cap; i++) 
                {
                    cmbseat.addItem(i);
                }
            }
            rs=st.executeQuery(" select Seat_num from TB_Booking where Rout_id=(select Rout_id from TB_Routinee where R_id=(select R_id from TB_Route where R_Name="+cmb+"))    ");
            
            while(rs.next())
            {
                int bseat = rs.getInt(1);
                cmbseat.removeItem(bseat);
            }
            
            
        } catch (SQLException ex) 
        {
            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error ! Please Try Again");
        }
       
    }//GEN-LAST:event_cmbrouteItemStateChanged

    private void cmbrouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbrouteActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cmbrouteActionPerformed

    private void cmbrouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbrouteMouseClicked
     
    }//GEN-LAST:event_cmbrouteMouseClicked

    private void cmblaststopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmblaststopMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmblaststopMouseClicked

    private void cmblaststopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmblaststopItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmblaststopItemStateChanged

    private void cmblaststopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblaststopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmblaststopActionPerformed

    private void btncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckActionPerformed
        // TODO add your handling code here:
          
        String cnic = "'" +  txtnic.getText() + "'";
        String fname = "'" +  txtfname.getText() + "'";
        String cmb= cmbnic.getSelectedItem().toString();
         
        
         
        if(cmb.equals("Name"))
        {
            try
        {    
            
        
        rs= st.executeQuery(" select Cust_Name,Cust_Age From TB_Customer where Cust_Name = "+cnic+" and Cust_fname= "+fname+"   ");

            if(rs.next())
            {
                String name = rs.getString(1);
                txtname.setText(name);
                txtage.setText(rs.getString(2));
               JOptionPane.showMessageDialog(this, "Customer Record Found ");
               
            
            }
            else
            {
            JOptionPane.showMessageDialog(this, "Incorrect Entry or Unregisted Customer"); 
           
            }
          
        }
        catch(SQLException | HeadlessException e)
            {
               JOptionPane.showMessageDialog(this, "Incorrect Entry or Unregisted Customer ! ");
               
            }
           
        }
        else if(cmb.equals("NIC"))
        {
            try
        {                  
        rs= st.executeQuery(" select Cust_Name,Cust_Age From TB_Customer where Cust_CNIC = "+cnic+" ");

            if(rs.next())
            {
                String name = rs.getString(1);
                txtname.setText(name);
                txtage.setText(rs.getString(2));
               JOptionPane.showMessageDialog(this, "Customer Nic number Found \n"
                       + "on the name of"
                       + " Mr :"+name);
            }
            
            else
            {
              JOptionPane.showMessageDialog(this, "Record Not Found or Unregisted Customer");  
               
            }
        }
        catch(SQLException | HeadlessException e)
            {
               JOptionPane.showMessageDialog(this, "Record Not Found or Unregisted Customer !");
              
            }
        }
        
        
       
        
    }//GEN-LAST:event_btncheckActionPerformed

    private void cmbnicItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbnicItemStateChanged
        // TODO add your handling code here:
       txtfname.setEditable(true);
       
        String cmb= cmbnic.getSelectedItem().toString();
        
        if(cmb.equals("Name"))
        {
        txtfname.setEditable(true);
        txtfname.setEnabled(true);
        }
        else
        {
        txtfname.setEditable(false);
        txtfname.setEnabled(false);
        }
        
    }//GEN-LAST:event_cmbnicItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncheck;
    private javax.swing.JComboBox cmblaststop;
    private javax.swing.JComboBox cmbnic;
    private javax.swing.JComboBox cmbroute;
    private javax.swing.JComboBox cmbseat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtavseats;
    private javax.swing.JTextField txtbook;
    private javax.swing.JTextField txtbusnum;
    private javax.swing.JLabel txtd;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtstartstop;
    private javax.swing.JLabel txtt;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics g, PageFormat pf, int page) throws PrinterException {
        
        
        if (page > 0) 
        { /* We have only one page, and 'page' is zero-based */
            return NO_SUCH_PAGE;
        }
        try {
            //getting Ticket From Database//
            rs=st.executeQuery("SELECT TOP 1 * FROM TB_Ticket ORDER BY Tp_ID DESC");
            while(rs.next())
            {
            Ticketid=rs.getString(1);    
            Name=rs.getString(3);
            Route=rs.getString(4);
            From=rs.getString(5);
            To=rs.getString(6);
            BusNum=rs.getString(7);
            Date=rs.getString(9);
            Time=rs.getString(10);
            BookDate=rs.getString(8);
            SeatNum=rs.getString(11);
            Price=rs.getString(12);
            }
        
        } catch (SQLException ex) {
            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Graphics2D g2d = (Graphics2D)g;
        g2d.translate(pf.getImageableX(), pf.getImageableY());
        Image img1;
        img1 = Toolkit.getDefaultToolkit().getImage("src//img//prntlogo.PNG");
        
        g.drawImage(img1,80,5, this);
        
        g.drawLine(45,100,310,100);
        g.drawLine(45,100,45,220);
        g.drawLine(45,220,310,220);
        g.drawLine(310,100,310,220);
        
        g.drawString("Ticket Number",50,110);
        g.drawString(Ticketid,200,110);
        
                g.drawString("Name",50,120); 
        g.drawString(Name,200,120);
        
                g.drawString("Route",50,133);
        g.drawString(Route,200,133);
        
                g.drawString("From",50,143);
        g.drawString(From,200,143);
        
                g.drawString("To",50,153);
        g.drawString(To,200,153);
        
                g.drawString("Bus Number",50,163);
        g.drawString(BusNum,200,163);
        
                g.drawString("Date Of Departure",50,173);
        g.drawString(Date,200,173);
        
                g.drawString("Time Of Departure",50,183);
        g.drawString(Time,200,183);
        
                g.drawString("Booking Date",50,193);
        g.drawString(BookDate,200,193);
        
                g.drawString("Seat Number",50,203);
        g.drawString(SeatNum,200,203);
        
                g.drawString("Price",50,213);
        g.drawString(Price,200,213);
        
        return PAGE_EXISTS;
    }
}
