/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mypack;

import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Wali
 */
public class EmpWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    Connection con=null;
    Statement st;
    ResultSet rs;
    
    public EmpWindow() 
    {
        initComponents();
        con= Connect.ConnectDB();
        try 
                {
              
            
            st = con.createStatement();
             String a="Online";
            rs = st.executeQuery("select Elogin_name from TB_EMPLOGIN where Elogin_status = '" + a +"' ");
                if(rs.next())
                {
                    empnametxt.setText(rs.getString(1));
                }
            
                }catch (SQLException ex) 
                {
                     JOptionPane.showMessageDialog(this, ex);
                } 
                DigitalClock digitalClock = new DigitalClock();
                 timepane.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
                timepane.add(digitalClock);
                
                ImageIcon img = new ImageIcon("src//img//logoforlogin.PNG");
                this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnviewcustomer = new javax.swing.JButton();
        btnaddcustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addbook = new javax.swing.JButton();
        btnadmin3 = new javax.swing.JButton();
        btnenquiry = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnemploye = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        empnametxt = new javax.swing.JLabel();
        btnvticket = new javax.swing.JButton();
        timepane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnenquiry1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Ticket Reservation System");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(100, 120, 0, 0));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        pane.setBackground(new java.awt.Color(255, 255, 255));
        pane.setForeground(new java.awt.Color(255, 255, 255));
        pane.setFocusTraversalPolicyProvider(true);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fback.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(11000, 8900));
        jLabel2.setMinimumSize(new java.awt.Dimension(11000, 8900));
        pane.add(jLabel2);
        jLabel2.setBounds(0, -70, 1380, 900);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnviewcustomer.setBackground(new java.awt.Color(0, 0, 0));
        btnviewcustomer.setFont(new java.awt.Font("Hobo Std", 1, 14)); // NOI18N
        btnviewcustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnviewcustomer.setText("View");
        btnviewcustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnviewcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewcustomerActionPerformed(evt);
            }
        });

        btnaddcustomer.setBackground(new java.awt.Color(0, 0, 0));
        btnaddcustomer.setFont(new java.awt.Font("Hobo Std", 1, 14)); // NOI18N
        btnaddcustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnaddcustomer.setText("Add");
        btnaddcustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnaddcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcustomerActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addcustomer.png"))); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Customer");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/create-ticket-icon.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Booking");

        addbook.setBackground(new java.awt.Color(0, 0, 0));
        addbook.setFont(new java.awt.Font("Hobo Std", 1, 14)); // NOI18N
        addbook.setForeground(new java.awt.Color(255, 255, 255));
        addbook.setText("Add");
        addbook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookActionPerformed(evt);
            }
        });

        btnadmin3.setBackground(new java.awt.Color(0, 0, 0));
        btnadmin3.setFont(new java.awt.Font("Hobo Std", 1, 14)); // NOI18N
        btnadmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin3.setText("Cancel");
        btnadmin3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmin3ActionPerformed(evt);
            }
        });

        btnenquiry.setBackground(new java.awt.Color(0, 0, 0));
        btnenquiry.setFont(new java.awt.Font("Hobo Std", 1, 14)); // NOI18N
        btnenquiry.setForeground(new java.awt.Color(255, 255, 255));
        btnenquiry.setText("Enquiry");
        btnenquiry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnenquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenquiryActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ticket.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enq.png"))); // NOI18N

        btnemploye.setBackground(new java.awt.Color(0, 0, 0));
        btnemploye.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnemploye.setForeground(new java.awt.Color(255, 255, 255));
        btnemploye.setText("Change Password");
        btnemploye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnemploye.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnemploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemployeActionPerformed(evt);
            }
        });

        btnlogout.setBackground(new java.awt.Color(0, 0, 0));
        btnlogout.setFont(new java.awt.Font("Hobo Std", 1, 13)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("SignOut");
        btnlogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogout.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnlogout.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        empnametxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empnametxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        empnametxt.setText("Employe");

        btnvticket.setBackground(new java.awt.Color(0, 0, 0));
        btnvticket.setFont(new java.awt.Font("Hobo Std", 1, 14)); // NOI18N
        btnvticket.setForeground(new java.awt.Color(255, 255, 255));
        btnvticket.setText("View Tickets");
        btnvticket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnvticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvticketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timepaneLayout = new javax.swing.GroupLayout(timepane);
        timepane.setLayout(timepaneLayout);
        timepaneLayout.setHorizontalGroup(
            timepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        timepaneLayout.setVerticalGroup(
            timepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Logged In As");

        btnenquiry1.setBackground(new java.awt.Color(0, 0, 0));
        btnenquiry1.setFont(new java.awt.Font("Hobo Std", 1, 14)); // NOI18N
        btnenquiry1.setForeground(new java.awt.Color(255, 255, 255));
        btnenquiry1.setText("Price List");
        btnenquiry1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnenquiry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenquiry1ActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/priceicon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnaddcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnadmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10))
                    .addComponent(btnvticket))
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnenquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(40, 40, 40)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4))
                    .addComponent(btnenquiry1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnemploye, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timepane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(empnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnlogout)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(btnaddcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnviewcustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addbook, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnvticket, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(empnametxt)
                .addGap(6, 6, 6)
                .addComponent(timepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnemploye, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnenquiry1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnenquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnemployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemployeActionPerformed
        // TODO add your handling code here:
        Changepass cpass=new Changepass();
        pane.add(cpass);
        cpass.setLocation(190,30);
        cpass.setVisible(true);
    }//GEN-LAST:event_btnemployeActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        String name = empnametxt.getText();
        String b="Offline";
        try {
            st.executeUpdate("Update TB_EMPLOGIN set Elogin_status ='"+b+"' where Elogin_name ='"+name+"' ");
            this.dispose();
            Login log=new Login();
            log.setLocation(300,200);
            log.setVisible(true);
            
             } catch (SQLException ex) {
            Logger.getLogger(EmpWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnenquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenquiryActionPerformed
        // TODO add your handling code here:
        Enquiry enq=new Enquiry();

        pane.add(enq);

        enq.setLocation(10,10);
        enq.setVisible(true);
    }//GEN-LAST:event_btnenquiryActionPerformed

    private void btnadmin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmin3ActionPerformed
        // TODO add your handling code here:
        UpdateBooking upbook=new UpdateBooking();
        pane.add(upbook);
        upbook.setLocation(250,130);
        upbook.setVisible(true);
    }//GEN-LAST:event_btnadmin3ActionPerformed

    private void addbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookActionPerformed
        // TODO add your handling code here:
        AddBooking ebook=new AddBooking();
        pane.add(ebook);
        ebook.setLocation(90,30);
        ebook.setVisible(true);
    }//GEN-LAST:event_addbookActionPerformed

    private void btnaddcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcustomerActionPerformed
        // TODO add your handling code here:
        AddCustomer acus=new AddCustomer();
        pane.add(acus);
        acus.setLocation(250,30);
        acus.setVisible(true);
    }//GEN-LAST:event_btnaddcustomerActionPerformed

    private void btnviewcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewcustomerActionPerformed
        // TODO add your handling code here:
        ViewCustomer vcus=new ViewCustomer();
        pane.add(vcus);
        vcus.setLocation(250,30);
        vcus.setVisible(true);
    }//GEN-LAST:event_btnviewcustomerActionPerformed

    private void btnvticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvticketActionPerformed
        // TODO add your handling code here:
         ViewTicket vtick=new ViewTicket();
        pane.add(vtick);
        vtick.setLocation(200,100);
        vtick.setVisible(true);
    }//GEN-LAST:event_btnvticketActionPerformed

    private void btnenquiry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenquiry1ActionPerformed
        // TODO add your handling code here:
        new PriceList().setVisible(false);
        PriceList plist=new PriceList();
        pane.add(plist);
        plist.setLocation(200,100);
        plist.setVisible(true);
    }//GEN-LAST:event_btnenquiry1ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {try {
            // select Look and Feel
            Properties props = new Properties();
  props.put("logoString", "");
  
            TextureLookAndFeel.setCurrentTheme(props);
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbook;
    private javax.swing.JButton btnaddcustomer;
    private javax.swing.JButton btnadmin3;
    private javax.swing.JButton btnemploye;
    private javax.swing.JButton btnenquiry;
    private javax.swing.JButton btnenquiry1;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnviewcustomer;
    private javax.swing.JButton btnvticket;
    private javax.swing.JLabel empnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JDesktopPane pane;
    private javax.swing.JPanel timepane;
    // End of variables declaration//GEN-END:variables
}
