/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mypack;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Wali
 */


public class Enquiry extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminLogin
     */
    
    Connection con=null;
    Statement st;
    ResultSet rs;
    ResultSet rs2;
    ResultSet rs3;
    ResultSet rs4;
    ResultSet rs5;
    
    public Enquiry() 
    {
        initComponents();
        con=Connect.ConnectDB();
         try 
        {
         st = con.createStatement();
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Update1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        searchbox2 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        bnametxt = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        BtnExit1 = new javax.swing.JButton();
        searchtxt2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        timetxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        rnametxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        routidtxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        stop1 = new javax.swing.JLabel();
        stop3 = new javax.swing.JLabel();
        stop2 = new javax.swing.JLabel();
        stop4 = new javax.swing.JLabel();
        stop5 = new javax.swing.JLabel();
        stop6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setTitle("Enquiry Window");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/enq.png"))); // NOI18N
        setVisible(false);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setText("Enquiry Window");

        Update1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        searchbox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Routinee Id", "Bus Number", "Route Name", "Date", "Time" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Search By ");

        bnametxt.setEditable(false);

        btnSearch1.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setText("Search");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        BtnExit1.setBackground(new java.awt.Color(0, 0, 0));
        BtnExit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnExit1.setForeground(new java.awt.Color(255, 255, 255));
        BtnExit1.setText("Exit");
        BtnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExit1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Bus Number ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("  Date");

        datetxt.setEditable(false);

        timetxt.setEditable(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Time");

        rnametxt.setEditable(false);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Route Name ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("(YY:MM:DD)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("(H:M:S)");

        routidtxt.setEditable(false);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Routinee ID");

        stop1.setBackground(new java.awt.Color(255, 255, 255));
        stop1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stop1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        stop3.setBackground(new java.awt.Color(255, 255, 255));
        stop3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stop3.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        stop2.setBackground(new java.awt.Color(255, 255, 255));
        stop2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stop2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        stop4.setBackground(new java.awt.Color(255, 255, 255));
        stop4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stop4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stop4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        stop5.setBackground(new java.awt.Color(255, 255, 255));
        stop5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stop5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stop5.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        stop6.setBackground(new java.awt.Color(255, 255, 255));
        stop6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stop6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stop6.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Stops Between this Route");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addComponent(searchbox2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(searchtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(routidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(timetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)))
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stop1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stop2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stop3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stop4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stop5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(stop6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(BtnExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(searchbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(searchtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch1))
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel24)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel19)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel23)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel21)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(routidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(bnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(rnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addComponent(stop1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(stop2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(stop3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(stop4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(stop5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(stop6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(BtnExit1))
        );

        javax.swing.GroupLayout Update1Layout = new javax.swing.GroupLayout(Update1);
        Update1.setLayout(Update1Layout);
        Update1Layout.setHorizontalGroup(
            Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Update1Layout.setVerticalGroup(
            Update1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Update1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Update1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Update1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
         clearlbl();
        cleartxtfield();
        String strbox = searchbox2.getSelectedItem().toString();

        if(strbox.equals(" "))
        {
               JOptionPane.showMessageDialog(this, "Error! \n " +
                       "Choose one Value From Combo Box \n to be searched");
                       searchbox2.requestFocus();
                       searchtxt2.setText(null);
        }
        else if(searchtxt2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Insert Value To Be Searched!");
            searchtxt2.requestFocus();
        }

        else if(strbox.equals("Routinee Id"))
        {
            try {
                rs = st.executeQuery("select * from TB_Routinee where Rout_ID = '" + searchtxt2.getText() + "'");
                
             if(rs.next())
            {   
                String a;
                routidtxt.setText(rs.getString(1));
                bnametxt.setText(rs.getString(2));
                rnametxt.setText(rs.getString(3));
                datetxt.setText(rs.getString(4));
                timetxt.setText(rs.getString(5));
                a=rs.getString(3);
               
                rs2 = st.executeQuery("select bus_number from TB_Buses where Bus_id = "+rs.getString(2)+"");
                if(rs2.next())
                {
                bnametxt.setText(rs2.getString(1));
                }
                rs3 = st.executeQuery("select R_Name from TB_Route where R_id = "+a+"");
                if(rs3.next())
                {
                rnametxt.setText(rs3.getString(1));
                }
                
                rs4 = st.executeQuery("select RC_StopName from TB_RouteCover where R_id = "+a+"");
                
                if(rs4.next())
                {
                    stop1.setText(rs4.getString(1));
                    if(rs4.next())
                    {
                    stop2.setText(rs4.getString(1));
                    }
                    if(rs4.next())
                    {
                    stop3.setText(rs4.getString(1));

                    }
                    if(rs4.next())
                    {
                    stop4.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop5.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop6.setText(rs4.getString(1)); 
                    }
                    
                }
                
                
            }
             else{
        JOptionPane.showMessageDialog(this,"Invalid Search Or Record Doesn't Exists ! !");
        searchtxt2.requestFocus();
                 }
            } catch (SQLException | HeadlessException ex) 
            {
            }
        }

        else if(strbox.equals("Bus Number"))
        {
            try {
                rs = st.executeQuery("select * from TB_Routinee where Bus_Id =(select Bus_id from TB_Buses where Bus_Number='" + searchtxt2.getText() + "' ) " );

             if(rs.next())
            {
                String a;
                routidtxt.setText(rs.getString(1));
                bnametxt.setText(rs.getString(2));
                rnametxt.setText(rs.getString(3));
                datetxt.setText(rs.getString(4));
                timetxt.setText(rs.getString(5));
                a=rs.getString(3);
                System.out.println("123");
                rs2 = st.executeQuery("select bus_number from TB_Buses where Bus_id = "+rs.getString(2)+"");
                if(rs2.next())
                {
                bnametxt.setText(rs2.getString(1));
                }
                rs3 = st.executeQuery("select R_Name from TB_Route where R_id = "+a+"");
                if(rs3.next())
                {System.out.println("1234");
                rnametxt.setText(rs3.getString(1));
                }
                rs4 = st.executeQuery("select RC_StopName from TB_RouteCover where R_id = "+a+"");
                
                if(rs4.next())
                {
                    stop1.setText(rs4.getString(1));
                    if(rs4.next())
                    {
                    stop2.setText(rs4.getString(1));
                    }
                    if(rs4.next())
                    {
                    stop3.setText(rs4.getString(1));

                    }
                    if(rs4.next())
                    {
                    stop4.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop5.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop6.setText(rs4.getString(1)); 
                    }
                    
                }
            }
             else
             {
              JOptionPane.showMessageDialog(this,"Invalid Entry");
              searchtxt2.requestFocus();
             }


            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Invalid Entry Or Record Doesnt Exists!");
            }
        }

        else if(strbox.equals("Route Name"))
        {
            try {
                rs = st.executeQuery("select * from TB_Routinee where R_id =(select R_id from TB_Route where R_Name= '" + searchtxt2.getText() + "' )");

             if(rs.next())
            {
                String a;
                routidtxt.setText(rs.getString(1));
                bnametxt.setText(rs.getString(2));
                rnametxt.setText(rs.getString(3));
                datetxt.setText(rs.getString(4));
                timetxt.setText(rs.getString(5));
                a=rs.getString(3);
                System.out.println("123");
                rs2 = st.executeQuery("select bus_number from TB_Buses where Bus_id = "+rs.getString(2)+"");
                if(rs2.next())
                {
                bnametxt.setText(rs2.getString(1));
                }
                rs3 = st.executeQuery("select R_Name from TB_Route where R_id = "+a+"");
                if(rs3.next())
                {System.out.println("1234");
                rnametxt.setText(rs3.getString(1));
                }
                rs4 = st.executeQuery("select RC_StopName from TB_RouteCover where R_id = "+a+"");
                
                if(rs4.next())
                {
                    stop1.setText(rs4.getString(1));
                    if(rs4.next())
                    {
                    stop2.setText(rs4.getString(1));
                    }
                    if(rs4.next())
                    {
                    stop3.setText(rs4.getString(1));

                    }
                    if(rs4.next())
                    {
                    stop4.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop5.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop6.setText(rs4.getString(1)); 
                    }
                    
                }
                
            }
             else
             {
              JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
              searchtxt2.requestFocus();
             }



            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Invalid Entry Or Record Doesnt Exists!");
            }
        }
        else if(strbox.equals("Date"))
        {
            try {
                rs = st.executeQuery("select * from TB_Routinee where Rout_Date = '" + searchtxt2.getText() + "'");

             if(rs.next())
            {
                
                String a;
                routidtxt.setText(rs.getString(1));
                bnametxt.setText(rs.getString(2));
                rnametxt.setText(rs.getString(3));
                datetxt.setText(rs.getString(4));
                timetxt.setText(rs.getString(5));
                a=rs.getString(3);
                System.out.println("123");
                rs2 = st.executeQuery("select bus_number from TB_Buses where Bus_id = "+rs.getString(2)+"");
                if(rs2.next())
                {
                bnametxt.setText(rs2.getString(1));
                }
                rs3 = st.executeQuery("select R_Name from TB_Route where R_id = "+a+"");
                if(rs3.next())
                {System.out.println("1234");
                rnametxt.setText(rs3.getString(1));
                }
                rs4 = st.executeQuery("select RC_StopName from TB_RouteCover where R_id = "+a+"");
                
                if(rs4.next())
                {
                    stop1.setText(rs4.getString(1));
                    if(rs4.next())
                    {
                    stop2.setText(rs4.getString(1));
                    }
                    if(rs4.next())
                    {
                    stop3.setText(rs4.getString(1));

                    }
                    if(rs4.next())
                    {
                    stop4.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop5.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop6.setText(rs4.getString(1)); 
                    }
                    
                }
                
            }
             else
             {
             JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
             searchtxt2.requestFocus();
             }


            } catch (SQLException ex) 
            {
                JOptionPane.showMessageDialog(this,"Invalid Entry Or Record Doesnt Exists!");
            }
        }

        else if(strbox.equals("Time"))
        {
            try {
                rs = st.executeQuery("select * from TB_Routinee where Rout_Time = '" + searchtxt2.getText() + "'");

            if(rs.next())
            {
               String a;
                routidtxt.setText(rs.getString(1));
                bnametxt.setText(rs.getString(2));
                rnametxt.setText(rs.getString(3));
                datetxt.setText(rs.getString(4));
                timetxt.setText(rs.getString(5));
                a=rs.getString(3);
                
                rs2 = st.executeQuery("select bus_number from TB_Buses where Bus_id = "+rs.getString(2)+"");
                if(rs2.next())
                {
                bnametxt.setText(rs2.getString(1));
                }
                rs3 = st.executeQuery("select R_Name from TB_Route where R_id = "+a+"");
                if(rs3.next())
                {
                rnametxt.setText(rs3.getString(1));
                }
                rs4 = st.executeQuery("select RC_StopName from TB_RouteCover where R_id = "+a+"");
                
                if(rs4.next())
                {
                    stop1.setText(rs4.getString(1));
                    if(rs4.next())
                    {
                    stop2.setText(rs4.getString(1));
                    }
                    if(rs4.next())
                    {
                    stop3.setText(rs4.getString(1));

                    }
                    if(rs4.next())
                    {
                    stop4.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop5.setText(rs4.getString(1)); 
                    }
                    if(rs4.next())
                    {
                    stop6.setText(rs4.getString(1)); 
                    }
                    
                }
            }
            else
            {
            JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
            searchtxt2.requestFocus();
            }


            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(this,"Invalid Entry Or Record Doesnt Exists!");
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this,"Invalid Search");
        }
        
        
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void BtnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnExit1ActionPerformed
public void clearlbl()
{
    stop1.setText("");
    stop2.setText("");
    stop3.setText("");
    stop4.setText("");
    stop5.setText("");
    stop6.setText("");
}
public void cleartxtfield()
{
    routidtxt.setText("");
    bnametxt.setText("");
    rnametxt.setText("");
    datetxt.setText("");
    timetxt.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit1;
    private javax.swing.JPanel Update1;
    private javax.swing.JTextField bnametxt;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField rnametxt;
    private javax.swing.JTextField routidtxt;
    private javax.swing.JComboBox searchbox2;
    private javax.swing.JTextField searchtxt2;
    private javax.swing.JLabel stop1;
    private javax.swing.JLabel stop2;
    private javax.swing.JLabel stop3;
    private javax.swing.JLabel stop4;
    private javax.swing.JLabel stop5;
    private javax.swing.JLabel stop6;
    private javax.swing.JTextField timetxt;
    // End of variables declaration//GEN-END:variables
}
