/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mypack;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Wali
 */
public class PriceList extends javax.swing.JInternalFrame  {

    /**
     * Creates new form AdminLogin
     */
    
    Connection con=null;
    Statement st;
    ResultSet rs;
 

    public PriceList() {
        initComponents();
        con=Connect.ConnectDB();
        try 
        {
         st = con.createStatement();
        
            
            rs=st.executeQuery("select R_Name from TB_Route");
            while(rs.next())
        {
        cmbroute.addItem(rs.getString(1));
        }
            
        
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, "Connection Error !");
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        cmbroute = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtbnum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttype = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstart = new javax.swing.JTextField();
        cmbstop = new javax.swing.JComboBox();
        txtd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(java.awt.SystemColor.inactiveCaption);
        setBorder(null);
        setClosable(true);
        setTitle("Booking");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adminicon.png"))); // NOI18N
        setVisible(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 51, 255));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cmbroute.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbroute.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbrouteItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Route");

        txtbnum.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bus Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Bus Type");

        txttype.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Starting Stop");

        txtstart.setEditable(false);

        cmbstop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", " " }));
        cmbstop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbstopItemStateChanged(evt);
            }
        });

        txtd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Stops");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Distance");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Price");

        txtp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setText("Check Price");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbroute, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtbnum, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtstart, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(30, 30, 30)
                                .addComponent(cmbstop, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(65, 65, 65)))))
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtp)
                                    .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)))
                        .addGap(169, 169, 169))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtbnum, txtstart});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(cmbroute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtbnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3))
                            .addComponent(txttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel5))
                            .addComponent(txtstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbstop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtd, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButton2))
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setText("Price List");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(221, 221, 221))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbrouteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbrouteItemStateChanged
        // TODO add your handling code here:
        cmbstop.removeAllItems();
        String cmb= "'" + cmbroute.getSelectedItem().toString()+ "'";
        try {
            
            
            if(cmbroute.getSelectedIndex()==0)
            {
                cmbstop.removeAllItems();
                txtd.setText("");
                txtp.setText("");
                txttype.setText("");
                txtbnum.setText("");
                txtstart.setText("");
                
            }
            
            
            rs=st.executeQuery("  select RC_StopName from TB_RouteCover where R_id=(select R_id from TB_Route where R_Name="+cmb+")  ");
          
            while(rs.next())
            {   
                
                cmbstop.addItem(rs.getString(1));
            }

            rs=st.executeQuery("  select Bus_Number from TB_Buses where bus_id=(select bus_id from TB_Routinee where R_id=(select R_id from TB_Route where R_Name="+cmb+"))    ");

            while(rs.next())
            {
                txtbnum.setText(rs.getString(1));
            }
            rs=st.executeQuery("  select Bus_type from TB_Buses where Bus_Number='"+txtbnum.getText()+"'   ");

            while(rs.next())
            {
                txttype.setText(rs.getString(1));
            }
            
            rs=st.executeQuery("  select R_Start from TB_Route where R_Name="+cmb+"  ");

            while(rs.next())
            {
                txtstart.setText(rs.getString(1));
            }
            
            
            
          /* rs=st.executeQuery("  select RC_StopName from TB_RouteCover where R_id=(select R_id from TB_Route where R_Name="+cmb+")  ");

            if(rs.next())
            {
                stop1.setText(rs.getString(1));
                if(rs.next())
                {
                  stop2.setText(rs.getString(1));
                }
                if(rs.next())
                {
                  stop3.setText(rs.getString(1));
                }
                if(rs.next())
                {
                  stop4.setText(rs.getString(1));
                }
                if(rs.next())
                {
                  stop5.setText(rs.getString(1));
                }
            }
            
            rs=st.executeQuery("  select RC_Dist_bw_Stops from TB_RouteCover where R_id=(select R_id from TB_Route where R_Name="+cmb+")  ");
            
            if(rs.next())
            {
                s1dis.setText(rs.getString(1));
                if(rs.next())
                {
                  s2dis.setText(rs.getString(1));
                }
                if(rs.next())
                {
                  s3dis.setText(rs.getString(1));
                }
                if(rs.next())
                {
                  s4dis.setText(rs.getString(1));
                }
                if(rs.next())
                {
                  s5dis.setText(rs.getString(1));
                }
            }
            
          
              
            
            
            rs=st.executeQuery("  select Bus_PricePerKm from TB_Buses where Bus_Number='"+txtbnum.getText()+"' ");
            
            if(rs.next())
            {   
                int price = (rs.getInt(1));
                int distance1= Integer.parseInt(s1dis.getText());
                int distance2= Integer.parseInt(s2dis.getText());
                int distance3= Integer.parseInt(s3dis.getText());
                int distance4= Integer.parseInt(s4dis.getText());
               // int distance5= Integer.parseInt(s5dis.getText());
                
                
                int p1= price*distance1;
                int p2= price*distance2;
                int p3= price*distance3;
                int p4= price*distance4;
                //int p5= price*distance5;
                
                
                s1p.setText(""+p1);
                s2p.setText(""+p2);
                s3p.setText(""+p3);
                s4p.setText(""+p4);
               // s5p.setText(""+p5);
                
              
                
            }*/
            

        } catch (SQLException ex)
        {
            Logger.getLogger(AddBooking.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error ! Please Try Again");
        }

    }//GEN-LAST:event_cmbrouteItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbstopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbstopItemStateChanged
        
            // TODO add your handling code here:
            
      /*    String cmbstp = "'" + cmbstop.getSelectedItem().toString()+ "'";
            
          try {   
            try {
                rs=st.executeQuery(" Select RC_Dist_bw_Stops from TB_RouteCover where RC_StopName="+cmbstp+"  ");
                
                while(rs.next())
                {
                    txtd.setText(rs.getString(1));
                }
               
                
                
         
            
            } catch (SQLException ex) 
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"aaaa");
            }
           
            rs=st.executeQuery("  select Bus_PricePerKm from TB_Buses where Bus_Number = '"+txtbnum.getText()+"'  ");
                
                 if(rs.next())
                 {
                     txtp.setText(rs.getString(1));
                     //int bprice=rs.getInt(1);
                     //int distance= Integer.parseInt(txtd.getText());
                     //int price= bprice*distance;
                     
                     //txtp.setText(price+"");
                 }
        } catch (SQLException ex) {
            ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"aaaa");
        }*/
        
    }//GEN-LAST:event_cmbstopItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String cmbstp = "'" + cmbstop.getSelectedItem().toString()+ "'";
            
          try {  
              
              /*if(cmbstop.getSelectedIndex()==0)
              {
                    JOptionPane.showMessageDialog(this,"Must Select Route");
              }*/
              
            try {
                rs=st.executeQuery(" Select RC_Dist_bw_Stops from TB_RouteCover where RC_StopName="+cmbstp+"  ");
                
                while(rs.next())
                {
                    int a= rs.getInt(1);
                    //txtd.setText(rs.getString(1));
                    txtd.setText(a+"");
                }
               
                
                
         
            
            } catch (SQLException ex) 
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"aaaa");
            }
           
            rs=st.executeQuery("  select Bus_PricePerKm from TB_Buses where Bus_Number = '"+txtbnum.getText()+"'  ");
                
                 if(rs.next())
                 {
                     
                    int bprice=rs.getInt(1);
                    String distance=(txtd.getText());
                    //float price= bprice*distance;
                    float p;
                    p=Float.parseFloat(distance);
                    float price = bprice*p;
                    
                    txtp.setText(price+"");
                 }
        } catch (SQLException ex) {
            ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"aaaa");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
   
 
     /*   public void clearfield()
    {
                txtname.setText("");
                txtroute.setText("");
                txtbusnum.setText("");
                txtfrom.setText("");
                txtto.setText("");
                txtseat.setText("");
                txtdate.setText("");
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbroute;
    private javax.swing.JComboBox cmbstop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtbnum;
    private javax.swing.JTextField txtd;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtstart;
    private javax.swing.JTextField txttype;
    // End of variables declaration//GEN-END:variables

    
    
}
