/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mypack;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wali
 */


public class ViewEmp extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminLogin
     */
    
    Connection con=null;
    Statement st;
    ResultSet rs;
    
    public ViewEmp() 
    {
        initComponents();
        con=Connect.ConnectDB();
         try 
        {
         st = con.createStatement();
        } catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(this, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        searchbox = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Update = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        searchbox1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        searchtxt2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        contacttxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        loctxt = new javax.swing.JTextField();
        quatxt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        nictxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setTitle("Employee Details");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adminicon.png"))); // NOI18N
        setVisible(false);

        jTabbedPane1.setToolTipText("dasdads");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 51, 255));

        searchbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Id", "Name", "Contact", "Location", "CNIC", "Email" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Search By : ");

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("View");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear Table");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Contact", "Location", "Qualification", "Age", "CNIC", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(102, 51, 255));

        searchbox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  ", "Id", "Name", "Contact", "Location", "CNIC", "Email" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Search By ");

        btnSearch1.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch1.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch1.setText("View");
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        searchtxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxt2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Employee Name ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Contact");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Location");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Qualification");

        idtxt.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Employee ID ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("CNIC");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Email");

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Reset");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nictxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton7)
                        .addGap(30, 30, 30)
                        .addComponent(jButton6)
                        .addGap(26, 26, 26)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(searchbox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(btnSearch1)
                    .addComponent(searchtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contacttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nictxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout UpdateLayout = new javax.swing.GroupLayout(Update);
        Update.setLayout(UpdateLayout);
        UpdateLayout.setHorizontalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UpdateLayout.setVerticalGroup(
            UpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Update", Update);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("View & Update Employee Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)tbl.getModel();
        tm.setNumRows(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
         DefaultTableModel tm = (DefaultTableModel)tbl.getModel();
         tm.setNumRows(0);
        String strbox = searchbox.getSelectedItem().toString();

        if(strbox.equals(" "))
        {
               JOptionPane.showMessageDialog(this, "Error! \n " +
                       "Choose one Value From Combo Box \n to be searched");
                       searchbox.requestFocus();
                       searchtxt.setText(null);
        }
        else if(searchtxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Insert Value To Be Searched!");
            searchtxt.requestFocus();
        }

        else if(strbox.equals("Id"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_id = '" + searchtxt.getText() + "'");
                
             if(rs.next())
            {
                tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
            }
             else{
        JOptionPane.showMessageDialog(this,"Invalid ID ! !");
        searchtxt.requestFocus();
             }
            } catch (Exception ex) {
  
                  ex.printStackTrace();
                
            }
        }

        else if(strbox.equals("Name"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_Name = '" + searchtxt.getText() + "'");

             if(rs.next())
            {
                tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
               
            }
             else
             {
              JOptionPane.showMessageDialog(this,"Invalid Entry");
              searchtxt.requestFocus();
             }


            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"Invalid Entry, Record Doesnt Exists!");
            }
        }

        else if(strbox.equals("Contact"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_Contact = '" + searchtxt.getText() + "'");

             if(rs.next())
              {
                tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
               
              }
             else
             {
              JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
              searchtxt.requestFocus();
             }



            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Invalid Entry, Record Doesnt Exists!");
            }
        }
        else if(strbox.equals("Location"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_Location = '" + searchtxt.getText() + "'");

             if(rs.next())
             {
                tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
                
                while(rs.next())
                {
                    tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                    , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                     rs.getString(8),rs.getString(9),rs.getString(10)});
                }
            }
             else
             {
             JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
             searchtxt.requestFocus();
             }


            } catch (SQLException ex) 
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"Invalid Entry , Record Doesnt Exists!");
            }
        }

        else if(strbox.equals("CNIC"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_CNIC = '" + searchtxt.getText() + "'");

            if(rs.next())
            {
                tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
                
                while(rs.next())
                {
                    tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                    , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                     rs.getString(8),rs.getString(9),rs.getString(10)});
                }
            }
            else
            {
            JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
            searchtxt.requestFocus();
            }


            } catch (SQLException ex) {
                ex.printStackTrace();
                 JOptionPane.showMessageDialog(this,"Invalid Entry, Record Doesnt Exists!");
            }

        }
        else if(strbox.equals("Email"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_Email = '" + searchtxt.getText() + "'");

             if(rs.next())
            {
                tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
                
                while(rs.next())
                {
                    tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                    , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                     rs.getString(8),rs.getString(9),rs.getString(10)});
                }
            }
             else
             {
             JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
             searchtxt.requestFocus();
             }


            } catch (SQLException ex) {
                ex.printStackTrace();
                 JOptionPane.showMessageDialog(this,"Invalid Entry, Record Doesnt Exists!");
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this,"Invalid Search");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
       // TODO add your handling code here:
        
        String strbox = searchbox1.getSelectedItem().toString();

        if(strbox.equals(" "))
        {
               JOptionPane.showMessageDialog(this, "Error! \n " +
                       "Choose one Value From Combo Box \n to be searched");
                       searchbox.requestFocus();
                       searchtxt2.setText(null);
        }
        else if(searchtxt2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please Insert Value To Be Searched!");
            searchtxt2.requestFocus();
        }

        else if(strbox.equals("Id"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_id = '" + searchtxt2.getText() + "'");
                
             if(rs.next())
            {
                idtxt.setText(rs.getString(1));
                nametxt.setText(rs.getString(3));
                contacttxt.setText(rs.getString(5));
                loctxt.setText(rs.getString(6));
                quatxt.setText(rs.getString(7));
                nictxt.setText(rs.getString(9));
                emailtxt.setText(rs.getString(10));
               
            }
             else{
        JOptionPane.showMessageDialog(this,"Invalid ID ! !");
        searchtxt2.requestFocus();
             }
            } catch (Exception ex) {
  
                  ex.printStackTrace();
                
            }
        }

        else if(strbox.equals("Name"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_Name = '" + searchtxt2.getText() + "'");

             if(rs.next())
            {
                idtxt.setText(rs.getString(1));
                nametxt.setText(rs.getString(3));
                contacttxt.setText(rs.getString(5));
                loctxt.setText(rs.getString(6));
                quatxt.setText(rs.getString(7));
                nictxt.setText(rs.getString(9));
                emailtxt.setText(rs.getString(10));
               
            }
             else
             {
              JOptionPane.showMessageDialog(this,"Invalid Entry");
              searchtxt2.requestFocus();
             }


            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"Invalid Entry, Record Doesnt Exists!");
            }
        }

        else if(strbox.equals("Contact"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_Contact = '" + searchtxt2.getText() + "'");

             if(rs.next())
              {
                idtxt.setText(rs.getString(1));
                nametxt.setText(rs.getString(3));
                contacttxt.setText(rs.getString(5));
                loctxt.setText(rs.getString(6));
                quatxt.setText(rs.getString(7));
                nictxt.setText(rs.getString(9));
                emailtxt.setText(rs.getString(10));
               
            }
             else
             {
              JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
              searchtxt2.requestFocus();
             }



            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,"Invalid Entry, Record Doesnt Exists!");
            }
        }
        else if(strbox.equals("Location"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_Location = '" + searchtxt2.getText() + "'");

             if(rs.next())
             {
                idtxt.setText(rs.getString(1));
                nametxt.setText(rs.getString(3));
                contacttxt.setText(rs.getString(5));
                loctxt.setText(rs.getString(6));
                quatxt.setText(rs.getString(7));
                nictxt.setText(rs.getString(9));
                emailtxt.setText(rs.getString(10));
            }
             else
             {
             JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
             searchtxt2.requestFocus();
             }


            } catch (SQLException ex) 
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"Invalid Entry , Record Doesnt Exists!");
            }
        }

        else if(strbox.equals("CNIC"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_CNIC = '" + searchtxt2.getText() + "'");

            if(rs.next())
            {
                idtxt.setText(rs.getString(1));
                nametxt.setText(rs.getString(3));
                contacttxt.setText(rs.getString(5));
                loctxt.setText(rs.getString(6));
                quatxt.setText(rs.getString(7));
                nictxt.setText(rs.getString(9));
                emailtxt.setText(rs.getString(10));
            }
            else
            {
            JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
            searchtxt2.requestFocus();
            }


            } catch (SQLException ex) {
                ex.printStackTrace();
                 JOptionPane.showMessageDialog(this,"Invalid Entry, Record Doesnt Exists!");
            }

        }
        else if(strbox.equals("Email"))
        {
            try {
                rs = st.executeQuery("select * from TB_employe where E_Email = '" + searchtxt2.getText() + "'");

             if(rs.next())
            {
                idtxt.setText(rs.getString(1));
                nametxt.setText(rs.getString(3));
                contacttxt.setText(rs.getString(5));
                loctxt.setText(rs.getString(6));
                quatxt.setText(rs.getString(7));
                nictxt.setText(rs.getString(9));
                emailtxt.setText(rs.getString(10));
            }
             else
             {
             JOptionPane.showMessageDialog(this,"Invalid Entry \n Please Try Again");
             searchtxt2.requestFocus();
             }


            } catch (SQLException ex) {
                ex.printStackTrace();
                 JOptionPane.showMessageDialog(this,"Invalid Entry, Record Doesnt Exists!");
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this,"Invalid Search");
        }
       
        
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
       
        String id= "'" + idtxt.getText() + "'";
        String name = "'" + nametxt.getText() + "'";
        String contact = "'" + contacttxt.getText() + "'";
        String location = "'" + loctxt.getText() + "'";
        String qualf = "'" + quatxt.getText() + "'";
        String cnic = "'" + nictxt.getText() + "'";
        String email = "'" + emailtxt.getText() + "'";
        
         Pattern p=Pattern.compile("[a-z0-9]{3,30}\\@{1}[a-z0-9]{3,20}\\.{1}[a-z]{2,3}");
         Matcher m=p.matcher(email);
         
         Pattern pCont=Pattern.compile("[0-9]{8,11}");
         Matcher mCont=pCont.matcher(contact);
         
         Pattern pNic=Pattern.compile("[0-9]{5}\\-{1}[0-9]{7}\\-[0-9]{1}");
         Matcher mNic=pNic.matcher(cnic);
        
        
        if(idtxt.getText().equals("") || nametxt.getText().equals("") || contacttxt.getText().equals("")
                || loctxt.getText().equals("") || quatxt.getText().equals("") || nictxt.getText().equals("")
                || emailtxt.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Fill All The Fields");
        }
        else if(!m.find())
        {
                JOptionPane.showMessageDialog(this, "Invalid Email");
        }
        else if(!mCont.find())
        {
            JOptionPane.showMessageDialog(this,"Invalid Contact Number");
        }
        
           else if(!mNic.find())
        {
            JOptionPane.showMessageDialog(this,"Invalid Nic Number");
        }
        else
        {
        try
                {

                st.executeUpdate("Update TB_employe set E_Name = "+name+" ,E_contact="+contact+",E_location="+location+",E_qualificaiton="+qualf+",E_CNIC="+cnic+",E_Email="+email+"where E_id = "+id+"    ");
                
                JOptionPane.showMessageDialog(this, "Employe details updated");
                clear();


                }catch(SQLException | HeadlessException e)
                {   
                    JOptionPane.showMessageDialog(this, "Error !");
                }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tm = (DefaultTableModel)tbl.getModel();
         tm.setNumRows(0);
         try {
                rs = st.executeQuery("select * from TB_employe");

             if(rs.next())
             {
                tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                rs.getString(8),rs.getString(9),rs.getString(10)});
                
                while(rs.next())
                {
                    tm.insertRow(tm.getRowCount(), new Object[]{rs.getString(1), rs.getString(3)
                    , rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),
                     rs.getString(8),rs.getString(9),rs.getString(10)});
                }
            }
             else
             {
             JOptionPane.showMessageDialog(this,"No Record Found");
             searchtxt2.requestFocus();
             }


            } catch (SQLException ex) 
            {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,"No Record Found !");
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchtxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxt2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton7ActionPerformed
public void clear()
{
    idtxt.setText("");
    nametxt.setText("");
    contacttxt.setText("");
    loctxt.setText("");
    quatxt.setText("");
    nictxt.setText("");
    emailtxt.setText("");
    searchtxt2.setText("");
    searchbox1.setSelectedIndex(-1);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Update;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JTextField contacttxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField loctxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField nictxt;
    private javax.swing.JTextField quatxt;
    private javax.swing.JComboBox searchbox;
    private javax.swing.JComboBox searchbox1;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField searchtxt2;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
